services:
  # Backend service
  - type: web
    name: telepathy-test
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --worker-class gevent --workers 1 --bind 0.0.0.0:$PORT --log-level debug --timeout 120
    healthCheckPath: /health
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        value: postgresql://postgres:txg8mfv2HDF.fzr!vjn@db.moataxbdkiohngptgdgs.supabase.co:5432/postgres
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ALLOWED_ORIGINS
        value: "*"
      - key: BASE_URL
        value: https://telepathy-test.onrender.com
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /*
        name: Access-Control-Allow-Methods
        value: "GET, POST, OPTIONS"
      - path: /*
        name: Access-Control-Allow-Headers
        value: "Content-Type"
      - path: /*
        name: X-Frame-Options
        value: "DENY"

  # Frontend service
  - type: web
    name: telepathy-test
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://telepathy-test-backend.onrender.com
      - key: REACT_APP_GOOGLE_CLIENT_ID
        sync: false
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: https://telepathy-test-backend.onrender.com

