services:
  # Backend service
  - type: web
    name: telepathy-test-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --worker-class gevent --workers 1 --bind 0.0.0.0:$PORT --log-level debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: telepathy-test-db
          property: connectionString
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ALLOWED_ORIGINS
        value: https://telepathy-test.onrender.com

  # Frontend service
  - type: web
    name: telepathy-test
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://telepathy-test-backend.onrender.com
      - key: REACT_APP_GOOGLE_CLIENT_ID
        sync: false
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: https://telepathy-test-backend.onrender.com

databases:
  - name: telepathy-test-db
    databaseName: telepathy_test
    user: telepathy_test
    plan: free
